export const seedCatalog = [
  {
    id: "nick-draake-pink-moon-place",
    artist: "Nick Drake",
    title: "Place to Be",
    album: "Pink Moon",
    year: 1972,
  },
  {
    id: "nick-drake-pink-moon",
    artist: "Nick Drake",
    title: "Pink Moon",
    album: "Pink Moon",
    year: 1972,
  },
  {
    id: "massive-attack-teardrop",
    artist: "Massive Attack",
    title: "Teardrop",
    album: "Mezzanine",
    year: 1998,
  },
  {
    id: "radiohead-how-to-disappear-completely",
    artist: "Radiohead",
    title: "How to Disappear Completely",
    album: "Kid A",
    year: 2000,
  },
  {
    id: "burial-archangel",
    artist: "Burial",
    title: "Archangel",
    album: "Untrue",
    year: 2007,
  },
  {
    id: "cocteau-twins-heaven-or-las-vegas",
    artist: "Cocteau Twins",
    title: "Heaven or Las Vegas",
    album: "Heaven or Las Vegas",
    year: 1990,
  },
  {
    id: "boards-of-canada-dayvan-cowboy",
    artist: "Boards of Canada",
    title: "Dayvan Cowboy",
    album: "The Campfire Headphase",
    year: 2005,
  },
  {
    id: "kendrick-lamar-sing-about-me",
    artist: "Kendrick Lamar",
    title: "Sing About Me, I'm Dying of Thirst",
    album: "good kid, m.A.A.d city",
    year: 2012,
  },
  {
    id: "fleetwood-mac-dreams",
    artist: "Fleetwood Mac",
    title: "Dreams",
    album: "Rumours",
    year: 1977,
  },
  {
    id: "portishead-roads",
    artist: "Portishead",
    title: "Roads",
    album: "Dummy",
    year: 1994,
  }
];